Filme_Locadora/Models/ErrorViewModel.cs
namespace Filme_Locadora.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Filme_Locadora/Controllers/ClientesController.cs
using Filme_Locadora.DataAccess;
using Microsoft.AspNetCore.Mvc;

namespace Filme_Locadora.Controllers
{
    public class ClientesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult Incluir()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Incluir(Tbclientes cliente)
        {
            if (cliente.Documento != null)
            {
                if (cliente.Documento.Length != 11 && cliente.Documento.Length != 14)
                {
                    //Só passa por aqui se o campo conter qntd de digitos diferentes de 11 ou 14.
                    ModelState.AddModelError("Documento", "O documento deve conter 11 ou 14 dígitos!");
                }
            }
            //Vem para cá DIRETAMENTE quando o campo contém 11 ou 14 digitos
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                DbClientes.Incluir(cliente);
                //LISTAR é o nome do método. ELe sai do action que voce está e vai para outro
                return RedirectToAction("Listar");
            }
            catch (Exception ex)
            {

                ViewBag.MensagemErro = ex.Message;
                //Quando voce tem um retorno view e passa como parametro a view, o parametro é o nome do arquivo(pág). Aqui ele não sai do action que está
                return View("_Error");
            }
        }
        public ActionResult Listar()
        {
            return View(DbClientes.Listar());
        }
        public ActionResult Alterar(string id)
        {
            return ExecutarAction(id, "Alterar");

        }
        [HttpPost]
        public ActionResult Alterar(Tbclientes cliente)
        {
            if (!ModelState.IsValid)
            {
                return View(cliente);
            }
            try
            {
                DbClientes.Alterar(cliente);
                //LISTAR é o nome do método. ELe sai do action que voce está e vai para outro
                return RedirectToAction("Listar");
            }
            catch (Exception ex)
            {

                ViewBag.MensagemErro = ex.Message;
                //Quando voce tem um retorno view e passa como parametro a view, o parametro é o nome do arquivo(pág). Aqui ele não sai do action que está
                return View("_Error");
            }

        }
        public ActionResult ExibirDetalhes(string id)
        {
            return ExecutarAction(id, "ExibirDetalhes");
        }
        public ActionResult Excluir(string id)
        {
            return ExecutarAction(id, "Excluir");
        }

        public ActionResult ExecutarAction(string id, string view)
        {
            try
            {
                if (string.IsNullOrEmpty(id))
                {
                    throw new Exception("É necessário informar o documento.");
                }

                var cliente = DbClientes.Buscar(id);
                if (cliente == null)
                {
                    throw new Exception("Nenhum cliente encontrado com o documento informado.");
                }
                return View(view, cliente);
            }
            catch (Exception ex)
            {
                ViewBag.MensagemErro = ex.Message;
                return View("_Error");
            }
        }
        [HttpPost]
        public ActionResult Excluir(Tbclientes cliente)
        {
            try
            {
                DbClientes.Excluir(cliente);
                return RedirectToAction("Listar");
            }
            catch (Exception ex)
            {

                ViewBag.MensagemErro = ex.Message;
                return View("_Error");
            }

        }
    }
}

Filme_Locadora/Controllers/FilmesController.cs
using Filme_Locadora.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Web;
using Filme_Locadora.Models;
using System;
using System.Collections.Generic;



namespace Filme_Locadora.Controllers
{
    public class FilmesController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Incluir()
        {
            //case sensitive. pegamos da classe categorias o tem Id e Descricao

            //Vamos encaminhar p view a lista de categorias pra que quando categoria for selecionada, o id faça parte do produto.
            ViewBag.ListaCategorias = new SelectList(DbFilmes.ListarCategorias(), "Id", "Descricao");
            return View();
        }
        //[HttpPost]
        //// POSTED DA IMAGEM 
        //public ActionResult Incluir(Tbfilmes filme, HttpPostedFileBase image)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return Incluir();
        //    }
        //    // IMAGEM 
        //    if (image != null)
        //    {
        //        filme.MimeType = image.ContentType;
        //        filme.Foto = new byte[image.ContentLength];

        //        //Copiando os bytes da imagem recebida como parâmetro, na propriedade foto.
        //        //Parâmetros: 1° Quem vai receber os bytes? | 2° A partir de posição que a gente vai começar a tratar esses bytes? | 3° Tratar até o final 
        //        image.InputStream.Read(filme.Foto, 0, image.ContentLength);
        //    }

        //    DbFilmes.Incluir(filme);
        //    return RedirectToAction("Listar");
        //}

        ////IMAGEM 
        //public FileResult BuscarProduto(int id)
        //{
        //    try
        //    {
        //        var produto = DbFilmes.Buscar(id);
        //        if (produto != null)
        //        {
        //            if (produto.Foto != null)
        //            {
        //                return File(produto.Foto, produto.MimeType);
        //            }
        //        }
        //        return File("~/Images/ND.png", "image/jpeg");
        //    }
        //    catch (Exception)
        //    {

        //        throw;
        //    }


        public ActionResult Listar()
        {
            return View(DbFilmes.Listar());
        }
    }

}

Filme_Locadora/Controllers/HomeController.cs
using Filme_Locadora.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Filme_Locadora.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Filme_Locadora/Views/Clientes/Alterar.cshtml
@model Filme_Locadora.Tbclientes

@{
    ViewData["Title"] = "Alterar Cliente";
}

<h2>Alterar dados do cliente</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Documento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Documento, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Documento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Alterar Cliente" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para o menu", "Index")
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Filme_Locadora/Views/Clientes/Excluir.cshtml
@model Filme_Locadora.Tbclientes

@{
    ViewBag.Title = "Excluir";
}
<h3 class="text-danger">Tem certeza que deseja remover o cliente @Model.Nome?</h3>
<div>
    <hr />

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.Documento)

        <div class="form-actions no-color">
            <input type="submit" value="Sim, excluir" class="btn btn-danger" /> |
            @Html.ActionLink("Não, voltar para a lista", "Listar")
        </div>
    }
</div>

Filme_Locadora/Views/Clientes/ExibirDetalhes.cshtml
@model Filme_Locadora.Tbclientes

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes do Cliente <span class=" text-primary">@Model.Nome</span></h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Documento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Documento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Voltar para a lista", "Listar")
</p>

Filme_Locadora/Views/Clientes/Incluir.cshtml
@model Filme_Locadora.Tbclientes

@{
    ViewData["Title"] = "Incluir Cliente";
}

<h1>Incluir Novo Cliente</h1>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Documento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Documento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Documento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Incluir Cliente" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para o menu", "Index")
</div>

Filme_Locadora/Views/Clientes/Index.cshtml
@{
    ViewBag.Title = "Clientes";
}

<h2>Gestão de Clientes - Escolha uma opção</h2>

<ul>
    <li>@Html.ActionLink("Cadastro de Clientes" , "Incluir" , "Clientes")</li>
    <li>@Html.ActionLink("Lista de Clientes" , "Listar", "Clientes")</li>
</ul>

Filme_Locadora/Views/Clientes/Listar.cshtml
@model IEnumerable<Filme_Locadora.Tbclientes>

@{
    ViewData["Title"] = "Listar Clientes";
}

<h1>Lista de Clientes</h1>

<p>
    @Html.ActionLink("Novo Cliente", "Incluir")
</p>
@* COLUNAS *@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Documento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Documento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Alterar", "Alterar", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Detalhes", "ExibirDetalhes", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Excluir", "Excluir", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }
</table>

Filme_Locadora/Views/Filmes/Incluir.cshtml
@model Filme_Locadora.Tbfilmes

@{
    ViewBag.Title = "Incluir Produto";
}

<h2>Incluir Novo Produto</h2>
@*
    Primeiro parâmetro é o incluir, action onde iremos enviar nossos dados.    
    Segundo parâmetro Produtos, que é o nome do controller.
    Terceiro parâmetro é o método de envio, que é o Post.
    Quarto parâmetro é html, porem so reconhece na renderização.
*@
@using (Html.BeginForm("Incluir", "Filmes", FormMethod.Post, new { enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdCategoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(
               model => model.IdCategoria,
              (SelectList)ViewBag.ListaCategorias,
              new { @class = "form-control" })
                     
                @Html.ValidationMessageFor(model => model.IdCategoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>
      @* DIV DA IMAGEM 
        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span>
                    <input type="file" name="image" class="form-control" />
                </span>
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div> *@

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Incluir Filme" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Voltar para o menu", "Index")
</div>

Filme_Locadora/Views/Filmes/Index.cshtml
@{
    ViewData["Title"] = "Filmes";
}

<h2>Gestão de Filmes - Escolha um opção</h2>


<ul>
    <li>@Html.ActionLink("Cadastro de Filmes", "Incluir", "Filmes")</li>
    <li>@Html.ActionLink("Lista de Filmes", "Listar", "Filmes")</li>
</ul>

Filme_Locadora/Views/Filmes/Listar.cshtml
@model IEnumerable<Filme_Locadora.Tbfilmes>

@{
    ViewData["Title"] = "Listar filmes";
}

<h2>Lista de Filmes</h2>

<p>
    @Html.ActionLink("Incluir novo filme", "Incluir")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Foto)
        </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Preco)
            </td>
            <td>
                 IMAGEM 
                <img src="@Url.Action("BuscarProduto", "Filmes", new { id = item.Id })" style="width:100px;" />
            </td>*@
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<script src="janela.js"</script>

Filme_Locadora/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Filme_Locadora/Views/Shared/_Error.cshtml
@{
    ViewBag.Title = "Erro";
}
@* Esta classe danger irá colocar o texto em vermelho  *@
<h2 class="text-danger">Ocorreu o seguinte erro:</h2>

@* Esta classe alert danger deixará o fundo vermelho *@
<div class="alert alert-danger">
    @ViewBag.MensagemErro    
</div>

Filme_Locadora/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Filme_Locadora</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Filme_Locadora.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Filme_Locadora</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Filmes" asp-action="Index">Filmes</a>
                        </li>
                        @*<li>@Html.ActionLink("Clientes","Index", "Clientes")</li>
                        <li>@Html.ActionLink("Produtos","Index", "Produtos")</li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Filme_Locadora - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>